apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: saveliy950/eureka-server:latest
          ports:
            - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  type: ClusterIP
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: eureka-server
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30000
  selector:
    app: eureka-server