services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    networks:
      - taxi_provider

  eureka-server:
    container_name: eureka-server
    image: eureka-server
    ports:
      - "8761:8761"
    networks:
      - taxi_provider

  api-gateway:
    container_name: api-gateway
    image: api-gateway
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8765:8765"
    depends_on:
      - eureka-server
    networks:
      - taxi_provider

  passenger-service:
    container_name: passenger-service
    image: passenger-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/passengers
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - postgres
    networks:
      - taxi_provider

  driver-service:
    container_name: driver-service
    image: driver-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/drivers
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - postgres
    networks:
      - taxi_provider

  ride-service:
    container_name: ride-service
    image: ride-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/rides
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - postgres
    networks:
      - taxi_provider

  rating-service:
    container_name: rating-service
    image: rating-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ratings
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - postgres
    networks:
      - taxi_provider

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - taxi_provider

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - taxi_provider

volumes:
  postgres:
    driver: local

networks:
  taxi_provider:
    driver: bridge