apiVersion: apps/v1
kind: Deployment
metadata:
  name: passenger-service
  labels:
    app: passenger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passenger-service
  template:
    metadata:
      labels:
        app: passenger-service
    spec:
      containers:
        - name: passenger-service
          image: saveliy950/passenger-service:latest
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eureka-server:8761/eureka
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/passengers_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: skademon
            - name: EUREKA_INSTANCE_HOSTNAME
              value: passenger-service
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: passenger-service
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: passenger-service