spring:
  application:
    name: rating-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/ratings
  liquibase:
    change-log: classpath:db/changelog/main-changelog.xml
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/taxi_provider_realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8084
  forward-headers-strategy: framework

service:
  passenger:
    name: passenger-service
    rating:
      url: http://localhost:8081/api/v1/passenger-ratings
  driver:
    name: driver-service
    rating:
      url: /api/v1/driver-ratings

resilience4j:
  retry:
    instances:
      saveDriverRating:
        max-attempts: 5
        wait-duration: 5000
      savePassengerRating:
        max-attempts: 5
        wait-duration: 5000
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState:
          seconds: 5
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

eureka:
  instance:
    hostname: rating-service
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  auth:
    converter:
      resource-id: taxi_provider_auth
      client-resource-id: realm-management
      principal-attribute: preferred_username