apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
  labels:
    app: driver-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
        - name: driver-service
          image: saveliy950/driver-service:latest
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eureka-server:8761/eureka
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/drivers_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: skademon
            - name: EUREKA_INSTANCE_HOSTNAME
              value: driver-service
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: driver-service
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: driver-service