pipeline {
    agent any
    tools {
        maven 'project_maven'
    }
    stages {
        stage('Clean') {
            steps {
                bat 'mvn clean -pi driver-service -am'
            }
        }
        stage('Clean') {
            steps {
                bat 'mvn install -pi driver-service -am'
            }
        }
    }
}