spring:
  application:
    name: driver-service
  datasource:
    url: jdbc:postgresql://localhost:5432/taxi_provider_db
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/main-changelog.xml
    enabled: true

server:
  port: 8082
  forward-headers-strategy: framework

eureka:
  instance:
    hostname: driver-service
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"