spring:
  application:
    name: driver-service
  datasource:
    url: jdbc:postgresql://localhost:5432/taxi_provider_db
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/main-changelog.xml
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/taxi_provider_realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  zipkin:
    enabled: true
    service.name: my-service
    sender.type: web
    base-url: http://localhost:9411
  sleuth:
    enabled: true
    sampler:
      probability: 1.0

server:
  port: 8082
  forward-headers-strategy: framework

eureka:
  instance:
    hostname: driver-service
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
jwt:
  auth:
    converter:
      resource-id: taxi_provider_auth
      client-resource-id: realm-management
      principal-attribute: preferred_username
logging:
  level:
    root: info