scrape_configs:
  - job_name: 'TaxiProviderMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8765']
        labels:
          application: 'Taxi provider'