spring:
  application:
    name: ride-service
  datasource:
    url: jdbc:postgresql://localhost:5432/taxi_provider_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: skademon
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/main-changelog.xml
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/taxi_provider_realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  mail:
    host: smtp.gmail.com
    port: 587
    username: skomlenok363@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8083
  forward-headers-strategy: framework

service:
  passenger:
    name: passenger-service
    url: /api/v1/passengers
  driver:
    name: driver-service
    url: /api/v1/drivers
  rating:
    name: rating-service
    url: /api/v1/ratings

resilience4j:
  retry:
    instances:
      passengerById:
        max-attempts: 5
        wait-duration: 5000
      driverById:
        max-attempts: 5
        wait-duration: 5000
      driverChangeStatus:
        max-attempts: 5
        wait-duration: 5000
      rateByDriver:
        max-attempts: 5
        wait-duration: 5000
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState:
          seconds: 3
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

eureka:
  instance:
    hostname: ride-service
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  auth:
    converter:
      resource-id: taxi_provider_auth
      client-resource-id: realm-management
      principal-attribute: preferred_username