apiVersion: apps/v1
kind: Deployment
metadata:
  name: ride-service
  labels:
    app: ride-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ride-service
  template:
    metadata:
      labels:
        app: ride-service
    spec:
      containers:
        - name: ride-service
          image: saveliy950/ride-service:latest
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eureka-server:8761/eureka
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/rides_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: skademon
            - name: EUREKA_INSTANCE_HOSTNAME
              value: ride-service
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: ride-service
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: ride-service